version: '3'
services:
  wordpress:
    image: wordpress-rtl
    container_name: wordpress-rtl
    restart: always
    volumes:
      - wordpress:/var/www/html/wordpress
    ports:
      - 80:80
    environment:
      Server_Name: localhost
      DB_NAME: 'wordpress-db'
      DB_USER: 'wordpress'
      DB_PASSWORD: 'password'
      DB_HOST: 'wordpressdb'

  database:
    image: mariadb:latest
    container_name: wordpressdb
    restart: always
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress-db
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
volumes:
  wordpress:
  database:



